[package]
name = "vq"
version = "0.1.1"
description = "A vector quantization library for Rust"
repository = "https://github.com/habedi/vq"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["vq", "vector-quantization", "clustering", "nearest-neighbor", "data-compression"]
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]
homepage = "https://github.com/habedi/vq"
documentation = "https://docs.rs/vq"
#categories = ["development-tools"]
edition = "2021"

[lib]
name = "vq"
path = "src/lib.rs"

[[bin]]
name = "vq"
path = "src/main.rs"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
ctor = "0.2.9"
rand = "0.9.0"
half = "2.4.1"
nalgebra = "0.33.2"
rayon = "1.10"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmarks"
harness = false
