[template]
cargo_generate_version = ">=0.10.0"

[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)"
# The username should be a valid GitHub username.
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.project-description]
type = "string"
prompt = "Project description"

[placeholders.project-name]
type = "string"
prompt = "Project name"
# The project name should be a valid Rust crate name.
regex = "^[a-zA-Z][a-zA-Z0-9_-]*$"

[placeholders.author-name]
type = "string"
prompt = "Author name"

[placeholders.author-email]
type = "string"
prompt = "Author email"
regex = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'crate_type == "bin"']
ignore = ["src/lib.rs"]

# Additional conditionals can be added below for more customization
