name: Linux Build

on:
  workflow_dispatch: { } # Allow manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Dependencies and Run Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make test
        continue-on-error: false

      - name: Build for Linux
        run: |
          make build
        continue-on-error: false

      - name: List Build Directory (for Debugging)
        run: ls -R target

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: template-rust-project-linux-amd64
          path: 'target/release/template-rust-project'
