name: Publish to Crates.io

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:

  # Run tests before publishing and only publish if tests pass
  call_tests:
    uses: ./.github/workflows/tests.yml

  publish:
    runs-on: ubuntu-latest

    # Try to publish only if the tests pass
    needs: call_tests
    if: success()

    # Setup trusted publishing
    environment: crates-io
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Publish to Crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish
